### ISSUE TITLE
Prevent displaying duplicate images

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/ala-bie-hub#50] opened 2023-07-12 03:59 UTC
**Background**

Browsing through the species page image gallery, particularly for commonly recorded species with many photos pulled into ALA, there can be numerous duplicate images. This has been an issue for years and appears to be a bug with no clear causation. It is unknown whether this is purely an issue with images pulled in from iNaturalist, or a broader bug that applies to all image providers.

It can be difficult to reliably find these duplicates when visiting an example page, as the order of images appears to change upon session. However, when loading more images, after a short time they become more evident. 

They tend to appear as groups of consecutive images duplicated in the gallery, however it may be that individual images are duplicated as well. 

**Example**
https://bie.ala.org.au/species/https://biodiversity.org.au/afd/taxa/e6aff6af-ff36-4ad5-95f2-2dfdcca8caff#gallery 

![Image](https://github.com/AtlasOfLivingAustralia/ux-ui/assets/8326394/33407c7b-89db-4f18-9cde-daff703e76b1)

This issue needs to be investigated, and a fix delivered to prevent the display of duplicates images across the BIE.

**Comment by adam-collins** [comment] 2023-07-18 00:13
pull request https://github.com/AtlasOfLivingAustralia/ala-bie-hub/pull/60

**Comment by TaniaGLaity** [comment] 2023-10-26 21:45
@adam-collins there still appear to be duplicate images - see [[Osphranter rufus : Red Kangaroo | Atlas of Living Australia (ala.org.au)](https://bie.ala.org.au/species/https:/biodiversity.org.au/afd/taxa/e6aff6af-ff36-4ad5-95f2-2dfdcca8caff)](url)

**Comment by adam-collins** [comment] 2023-10-26 22:17
- Each unique visit the a BIE page can have unique gallery images. 
- Occurrence with similar but not duplicate images https://biocache.ala.org.au/occurrences/68a03a1b-ed20-4b33-858a-9e06084af778, source https://www.inaturalist.org/observations/121717858
- Inferred duplicate occurrence and the occurrence it is an inferred duplicate of having a similar or the same image for each occurrence https://biocache.ala.org.au/occurrences/49130828-b6f2-413a-b6a6-3e2c36f1015b, https://biocache.ala.org.au/occurrences/a5fc8835-fde2-43e9-a1cb-bd269f5cfa32
- Another occurrence with similar but not duplicate images https://biocache.ala.org.au/occurrences/7c238609-fe7e-4623-88a0-3d8265f13d91, source https://www.inaturalist.org/observations/180849911
- Multiple images for each occurrence are included because they were requested in the last round of changes. This also solves an otherwise unsolvable issue of including the first image that appears on source inaturalist pages.
- There is an occurrence filter that can be changed `var IMAGE_FILTER = '&fq=spatiallyValid:true&fq=-user_assertions:50001&fq=-user_assertions:50005'`, possibly to one of the data quality filters e.g. `qualityProfile=ALA`.

**Comment by TaniaGLaity** [comment] 2023-10-27 00:01
is there a way to not show duplicates in the gallery? ie not show inferred occurrence ones? such as your example:

Inferred duplicate occurrence and the occurrence it is an inferred duplicate of having a similar or the same image for each occurrence https://biocache.ala.org.au/occurrences/49130828-b6f2-413a-b6a6-3e2c36f1015b,
https://biocache.ala.org.au/occurrences/a5fc8835-fde2-43e9-a1cb-bd269f5cfa32

**Comment by adam-collins** [comment] 2023-10-27 01:38
Yes, by changing the filter. Is the `qualityProfile=ALA` suitable or too aggressive?

**Comment by TaniaGLaity** [comment] 2023-10-27 02:26
I think it's fine - seems to be doing it anyway now... (unless you just changed it?)

**Comment by adam-collins** [comment] 2023-10-27 03:50
If I understand your statement correctly, that suggested filter will do what you want, in addition to what is done now, and also filter out some additional items as described by the quality profile.

The actual change requires
- Making this line configurable https://github.com/AtlasOfLivingAustralia/ala-bie-hub/blob/develop/grails-app/assets/javascripts/species.show.js#L16
- Change the current value to also exclude implied duplicates (see ALA quality profile for the exact fq statement)
- Use the current value as the default in case of living atlas deployments
- Change this value in ansible-inventories to `&qualityProfile=ALA`

**Comment by adam-collins** [comment] 2023-11-09 05:06
on test, pull request https://github.com/AtlasOfLivingAustralia/ala-bie-hub/pull/106

**Closed** 2024-04-01 21:38 UTC
Labels: content-improvement
